<?php
			
	/**
	 * Generated by Getz Framework
	 * 
	 * @author Mario Sakamoto <mskamot@gmail.com>
	 * @see https://wtag.com.br/getz 
	 */
	 
	namespace src\model; 
	
	use src\model;
	
	class Estabelecimento_produtos_precoDao {
	
		private $connection;
		
		/*
		 * Constant variables
		 */
		private $create = "INSERT INTO estabelecimento_produtos_preco (
				preco
				, cadastrado
				, modificado
				, estabelecimeto_produtos
				) VALUES";
				
		public $read = 
				"estabelecimento_produtos_preco.id AS \"estabelecimento_produtos_preco.id\"
				, estabelecimento_produtos_preco.preco AS \"estabelecimento_produtos_preco.preco\"
				, estabelecimento_produtos_preco.cadastrado AS \"estabelecimento_produtos_preco.cadastrado\"
				, estabelecimento_produtos_preco.modificado AS \"estabelecimento_produtos_preco.modificado\"
				, estabelecimento_produtos_preco.estabelecimeto_produtos AS \"estabelecimento_produtos_preco.estabelecimeto_produtos\"
				";
				
		private $update = "UPDATE estabelecimento_produtos_preco SET";
		private $delete = "DELETE FROM estabelecimento_produtos_preco";
		
		public $from = "estabelecimento_produtos_preco estabelecimento_produtos_preco";
		
		/*
		 * Parameters
		 */
		private $where;
		private $order;
		
		// Dynamic query
		private $sql;
		
		// Controller response
		private $response;	
		
		/**
		 * @param {Object} connection
		 */
		public function __construct($connection) {
			$this->connection = $connection;
		}

		/**
		 * @param {Estabelecimento_produtos_preco}estabelecimento_produtos_preco
		 */
		public function setCreate($estabelecimento_produtos_preco) {		
			$this->sql = $this->create . " (\"" . 
					$estabelecimento_produtos_preco->getPreco() .
					"\", \"" . $estabelecimento_produtos_preco->getCadastrado() .
					"\", \"" . $estabelecimento_produtos_preco->getModificado() .
					"\", \"" . $estabelecimento_produtos_preco->getEstabelecimeto_produtos() .
					"\")";
		}
		
		/**
		 * @return {String}
		 */
		public function getCreate() {
			return $this->sql;
		}	
		
		/**
		 * @param {String} where
		 * @param {String} order
		 */
		public function setRead($where, $order) {
			$estabelecimento_produtosDao = new model\Estabelecimento_produtosDao($this->connection);
			
			$this->setWhere($where);
			$this->setOrder($order);
			
			$this->sql = "SELECT " . $this->read . ", " . $estabelecimento_produtosDao->read . 
					" FROM " . $this->getFrom() .", " . $estabelecimento_produtosDao->from . 
					($this->getWhere() == "" ? " WHERE estabelecimento_produtos_preco.estabelecimeto_produtos = estabelecimento_produtos.id" : $this->getWhere()) . 
					" AND estabelecimento_produtos_preco.estabelecimeto_produtos = estabelecimento_produtos.id" . $this->getOrder();
		}
		
		/**
		 * @return {String}
		 */
		public function getRead() {
			return $this->sql;
		}
		
		/**
		 * @param {Estabelecimento_produtos_preco}estabelecimento_produtos_preco  
		 * @param {String} where
		 */
		public function setUpdate($estabelecimento_produtos_preco, $where) {
			$this->setWhere($where);
			
			$this->sql = $this->update . 
					" id = \"" . $estabelecimento_produtos_preco->getId() . 
					"\", preco = \"" . $estabelecimento_produtos_preco->getPreco() . 
					"\", modificado = \"" . $estabelecimento_produtos_preco->getModificado() . 
					"\", estabelecimeto_produtos = \"" . $estabelecimento_produtos_preco->getEstabelecimeto_produtos() . 
					"\"" . $this->getWhere();
		}
		
		/**
		 * @return {String}
		 */
		public function getUpdate() {
			return $this->sql;
		}
		
		/**
		 * @param {String} where
		 */
		public function setDelete($where) {	
			$this->setWhere($where);
			
			$this->sql = $this->delete . $this->getWhere();
		}
		
		/**
		 * @return {String}
		 */
		public function getDelete() {
			return $this->sql;
		}
		
		/**
		 * @return {String}
		 */
		public function getFrom() {
			return $this->from;
		}
		
		/**
		 * @param {String} where
		 */
		public function setWhere($where) {
			if ($where != "")
				$this->where = " WHERE " . $where;
			else
				$this->where = "";
		}
		
		/**
		 * @return {String}
		 */
		public function getWhere() {
			return $this->where;
		}
		
		/**
		 * @param {String} order
		 */
		public function setOrder($order) {
			if ($order != "")
				$this->order = " ORDER BY " . $order;
			else
				$this->order = "";
		}
		
		/**
		 * @return {String}
		 */
		public function getOrder() {
			return $this->order;
		}
		
		/**
		 * @param {Integer} line
		 * @param column String
		 * @param value String
		 */
		private function setResponse($line, $column, $value) {
			$this->response[$line][$column] = $value;
		}

		/**
		 * @return {Array}
		 */
		private function getResponse() {
			return $this->response;
		}

		/**
		 * @param {String} where
		 */
		private function setSize($where) {
			$this->setWhere($where);
			
			$result = $this->connection->execute(
					"SELECT count(1) AS \"estabelecimento_produtos_preco.size\" from estabelecimento_produtos_preco" . $this->getWhere());

			while ($row = $result->fetch_assoc()) {		
				$this->setResponse(0, "estabelecimento_produtos_preco.size", $row["estabelecimento_produtos_preco.size"]);
				
				$pages = ceil($row["estabelecimento_produtos_preco.size"] / $this->connection->getItensPerPage());
				
				$this->setResponse(0, "estabelecimento_produtos_preco.page", $this->connection->getPosition());
				$this->setResponse(0, "estabelecimento_produtos_preco.pages", $pages);
				
				$pagination = "<select id='gz-select-pagination' onchange='goPage();'>";
				
				for ($i = 1; $i <= $pages; $i++) {
					if ($i == $this->connection->getPosition())
						$pagination .= "<option value='" . $i . "' selected>" . $i . "</option>";
					else
						$pagination .= "<option value='" . $i . "'>" . $i . "</option>";
				}	

				$pagination .= "</select>";
						
				$this->setResponse(0, "estabelecimento_produtos_preco.pagination", $pagination);
			}

			$this->connection->free($result);
		}
		
		/**
		 * @param {Integer} line
		 */
		public function setDivLine($line) {
			$this->setResponse($line - 1, "@_START_LINE_TWO", modelStartLine($line, 2));
			$this->setResponse($line - 1, "@_END_LINE_TWO", modelEndLine($line, 2));

			$this->setResponse($line - 1, "@_START_LINE_THREE", modelStartLine($line, 3));
			$this->setResponse($line - 1, "@_END_LINE_THREE", modelEndLine($line, 3));
			
			$this->setResponse($line - 1, "@_START_LINE_FOUR", modelStartLine($line, 4));
			$this->setResponse($line - 1, "@_END_LINE_FOUR", modelEndLine($line, 4));
		}
		
		/**
		 * @param {Integer} line
		 */
		public function checkDivLine($line) {
			if (modelCheckEndLine($line, 2) != "")
				$this->setResponse($line - 1, "@_END_LINE_TWO", modelCheckEndLine($line, 2));
			
			if (modelCheckEndLine($line, 3) != "")
				$this->setResponse($line - 1, "@_END_LINE_THREE", modelCheckEndLine($line, 3));		

			if (modelCheckEndLine($line, 4) != "")
				$this->setResponse($line - 1, "@_END_LINE_FOUR", modelCheckEndLine($line, 4));			
		}	

		/**
		 * @param {String} log
		 */
		private function setLog($log) {
			$this->setResponse(0, "log", $log);
		}
		
		/**
		 * @param {Estabelecimento_produtos_preco} estabelecimento_produtos_preco 
		 * @return {Boolean}
		 */
		public function create($estabelecimento_produtos_preco) {
			$result = "";

			$this->setCreate($estabelecimento_produtos_preco);
			$result = $this->connection->execute($this->getCreate());
			
			return $result;
		}

		/**
		 * @param {String} where
		 * @param {String} order
		 * @param {Boolean} wp
		 * @param {Array}
		 */
		public function read($where, $order, $wp) {
			$line = 0;

		
			
			$this->setRead($where, $order);

			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($line, "estabelecimento_produtos_preco.id", $row["estabelecimento_produtos_preco.id"]);
				$this->setResponse($line, "estabelecimento_produtos_preco.preco", modelDouble($row["estabelecimento_produtos_preco.preco"]));
				$this->setResponse($line, "estabelecimento_produtos_preco.cadastrado", modelDateTime($row["estabelecimento_produtos_preco.cadastrado"]));
				$this->setResponse($line, "estabelecimento_produtos_preco.modificado", modelDateTime($row["estabelecimento_produtos_preco.modificado"]));
				$this->setResponse($line, "estabelecimento_produtos_preco.estabelecimeto_produtos", $row["estabelecimento_produtos_preco.estabelecimeto_produtos"]);
				// $this->setResponse($line, "estabelecimento_produtos.estabelecimeto_produtos", $row["estabelecimento_produtos.estabelecimeto_produtos"]);
			
				$this->setResponse($line, "estabelecimento_produtos_preco.line", $line);
			
				$line++;
				
				if ($wp)
					$this->setDivLine($line);
			}

			$this->connection->free($result);
			
			if ($wp && $line > 0) {
				$this->checkDivLine($line);
				
				$this->setSize($where);
			}

			return $this->getResponse();
		}

		/**
		 * @param {Estabelecimento_produtos_preco} estabelecimento_produtos_preco 
		 * @return {Boolean}
		 */
		public function update($estabelecimento_produtos_preco) {
			$result = "";
			
			$this->setUpdate($estabelecimento_produtos_preco, "estabelecimento_produtos_preco.id = " . $estabelecimento_produtos_preco->getId());
			$result = $this->connection->execute($this->getUpdate());

			return $result;
		}

		/**
		 * @param {String} where
		 * @return {Boolean}
		 */
		public function delete($where) {
			$result = "";
			
			$this->setDelete($where);
			$result = $this->connection->execute($this->getDelete());

			return $result;
		}
		
		/**
		 * @param {Integer} selected
		 * @param {String} order
		 * @return {Array}
		 */
		public function combo($selected, $order) {
			$size = 0;

			$this->setRead("", $order);
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($size, "estabelecimento_produtos_preco.id", $row["estabelecimento_produtos_preco.id"]);
				$this->setResponse($size, "estabelecimento_produtos_preco.preco", $row["estabelecimento_produtos_preco.preco"]);
			
				if ($row["estabelecimento_produtos_preco.id"] == $selected)
					$this->setResponse($size, "estabelecimento_produtos_preco.selected", "selected");
				else
					$this->setResponse($size, "estabelecimento_produtos_preco.selected", "");
					
				$size++;
			}
			
			$this->connection->free($result);
			
			$this->setResponse(0, "size", $size);

			return $this->getResponse();
		}
		
		/**
		 * @param {String} where
		 * @return {Array}
		 */
		public function comboScr($where) {
			$size = 0;

			$this->setRead($where, "");
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($size, "estabelecimento_produtos_preco.id", $row["estabelecimento_produtos_preco.id"]);
				$this->setResponse($size, "estabelecimento_produtos_preco.preco", $row["estabelecimento_produtos_preco.preco"]);
				$this->setResponse($size, "estabelecimento_produtos_preco.selected", "selected");
					
				$size++;
			}
			
			$this->connection->free($result);
			
			$this->setResponse(0, "size", $size);

			return $this->getResponse();
		}

	}

?>