<?php
			
	/**
	 * Generated by Getz Framework
	 * 
	 * @author Mario Sakamoto <mskamot@gmail.com>
	 * @see https://wtag.com.br/getz 
	 */
	 
	namespace src\model; 
	
	use src\model;
	
	class Estabelecimento_produtosDao {
	
		private $connection;
		
		/*
		 * Constant variables
		 */
		private $create = "INSERT INTO estabelecimento_produtos (
				cadastro
				, modificado
				, estabelecimento
				, produto
				) VALUES";
				
		public $read = 
				"estabelecimento_produtos.id AS \"estabelecimento_produtos.id\"
				, estabelecimento_produtos.cadastro AS \"estabelecimento_produtos.cadastro\"
				, estabelecimento_produtos.modificado AS \"estabelecimento_produtos.modificado\"
				, estabelecimento_produtos.estabelecimento AS \"estabelecimento_produtos.estabelecimento\"
				, estabelecimento_produtos.produto AS \"estabelecimento_produtos.produto\"
				";
				
		private $update = "UPDATE estabelecimento_produtos SET";
		private $delete = "DELETE FROM estabelecimento_produtos";
		
		public $from = "estabelecimento_produtos estabelecimento_produtos";
		
		/*
		 * Parameters
		 */
		private $where;
		private $order;
		
		// Dynamic query
		private $sql;
		
		// Controller response
		private $response;	
		
		/**
		 * @param {Object} connection
		 */
		public function __construct($connection) {
			$this->connection = $connection;
		}

		/**
		 * @param {Estabelecimento_produtos}estabelecimento_produtos
		 */
		public function setCreate($estabelecimento_produtos) {		
			$this->sql = $this->create . " (\"" . 
					$estabelecimento_produtos->getCadastro() .
					"\", \"" . $estabelecimento_produtos->getModificado() .
					"\", \"" . $estabelecimento_produtos->getEstabelecimento() .
					"\", \"" . $estabelecimento_produtos->getProduto() .
					"\")";
		}
		
		/**
		 * @return {String}
		 */
		public function getCreate() {
			return $this->sql;
		}	
		
		/**
		 * @param {String} where
		 * @param {String} order
		 */
		public function setRead($where, $order) {
			$estabelecimentosDao = new model\EstabelecimentosDao($this->connection);
			$produtosDao = new model\ProdutosDao($this->connection);
			
			$this->setWhere($where);
			$this->setOrder($order);
			
			$this->sql = "SELECT " . $this->read . ", " . $estabelecimentosDao->read . ", " . $produtosDao->read . 
					" FROM " . $this->getFrom() .", " . $estabelecimentosDao->from . ", " . $produtosDao->from . 
					($this->getWhere() == "" ? " WHERE estabelecimento_produtos.estabelecimento = estabelecimentos.id AND estabelecimento_produtos.produto = produtos.id" : $this->getWhere()) . 
					" AND estabelecimento_produtos.estabelecimento = estabelecimentos.id AND estabelecimento_produtos.produto = produtos.id" . $this->getOrder();
		}
		
		/**
		 * @return {String}
		 */
		public function getRead() {
			return $this->sql;
		}
		
		/**
		 * @param {Estabelecimento_produtos}estabelecimento_produtos  
		 * @param {String} where
		 */
		public function setUpdate($estabelecimento_produtos, $where) {
			$this->setWhere($where);
			
			$this->sql = $this->update . 
					" id = \"" . $estabelecimento_produtos->getId() . 
					"\", cadastro = \"" . $estabelecimento_produtos->getCadastro() . 
					"\", modificado = \"" . $estabelecimento_produtos->getModificado() . 
					"\", estabelecimento = \"" . $estabelecimento_produtos->getEstabelecimento() . 
					"\", produto = \"" . $estabelecimento_produtos->getProduto() . 
					"\"" . $this->getWhere();
		}
		
		/**
		 * @return {String}
		 */
		public function getUpdate() {
			return $this->sql;
		}
		
		/**
		 * @param {String} where
		 */
		public function setDelete($where) {	
			$this->setWhere($where);
			
			$this->sql = $this->delete . $this->getWhere();
		}
		
		/**
		 * @return {String}
		 */
		public function getDelete() {
			return $this->sql;
		}
		
		/**
		 * @return {String}
		 */
		public function getFrom() {
			return $this->from;
		}
		
		/**
		 * @param {String} where
		 */
		public function setWhere($where) {
			if ($where != "")
				$this->where = " WHERE " . $where;
			else
				$this->where = "";
		}
		
		/**
		 * @return {String}
		 */
		public function getWhere() {
			return $this->where;
		}
		
		/**
		 * @param {String} order
		 */
		public function setOrder($order) {
			if ($order != "")
				$this->order = " ORDER BY " . $order;
			else
				$this->order = "";
		}
		
		/**
		 * @return {String}
		 */
		public function getOrder() {
			return $this->order;
		}
		
		/**
		 * @param {Integer} line
		 * @param column String
		 * @param value String
		 */
		private function setResponse($line, $column, $value) {
			$this->response[$line][$column] = $value;
		}

		/**
		 * @return {Array}
		 */
		private function getResponse() {
			return $this->response;
		}

		/**
		 * @param {String} where
		 */
		private function setSize($where) {
			$this->setWhere($where);
			
			$result = $this->connection->execute(
					"SELECT count(1) AS \"estabelecimento_produtos.size\" from estabelecimento_produtos" . $this->getWhere());

			while ($row = $result->fetch_assoc()) {		
				$this->setResponse(0, "estabelecimento_produtos.size", $row["estabelecimento_produtos.size"]);
				
				$pages = ceil($row["estabelecimento_produtos.size"] / $this->connection->getItensPerPage());
				
				$this->setResponse(0, "estabelecimento_produtos.page", $this->connection->getPosition());
				$this->setResponse(0, "estabelecimento_produtos.pages", $pages);
				
				$pagination = "<select id='gz-select-pagination' onchange='goPage();'>";
				
				for ($i = 1; $i <= $pages; $i++) {
					if ($i == $this->connection->getPosition())
						$pagination .= "<option value='" . $i . "' selected>" . $i . "</option>";
					else
						$pagination .= "<option value='" . $i . "'>" . $i . "</option>";
				}	

				$pagination .= "</select>";
						
				$this->setResponse(0, "estabelecimento_produtos.pagination", $pagination);
			}

			$this->connection->free($result);
		}
		
		/**
		 * @param {Integer} line
		 */
		public function setDivLine($line) {
			$this->setResponse($line - 1, "@_START_LINE_TWO", modelStartLine($line, 2));
			$this->setResponse($line - 1, "@_END_LINE_TWO", modelEndLine($line, 2));

			$this->setResponse($line - 1, "@_START_LINE_THREE", modelStartLine($line, 3));
			$this->setResponse($line - 1, "@_END_LINE_THREE", modelEndLine($line, 3));
			
			$this->setResponse($line - 1, "@_START_LINE_FOUR", modelStartLine($line, 4));
			$this->setResponse($line - 1, "@_END_LINE_FOUR", modelEndLine($line, 4));
		}
		
		/**
		 * @param {Integer} line
		 */
		public function checkDivLine($line) {
			if (modelCheckEndLine($line, 2) != "")
				$this->setResponse($line - 1, "@_END_LINE_TWO", modelCheckEndLine($line, 2));
			
			if (modelCheckEndLine($line, 3) != "")
				$this->setResponse($line - 1, "@_END_LINE_THREE", modelCheckEndLine($line, 3));		

			if (modelCheckEndLine($line, 4) != "")
				$this->setResponse($line - 1, "@_END_LINE_FOUR", modelCheckEndLine($line, 4));			
		}	

		/**
		 * @param {String} log
		 */
		private function setLog($log) {
			$this->setResponse(0, "log", $log);
		}
		
		/**
		 * @param {Estabelecimento_produtos} estabelecimento_produtos 
		 * @return {Boolean}
		 */
		public function create($estabelecimento_produtos) {
			$result = "";

			$this->setCreate($estabelecimento_produtos);
			$result = $this->connection->execute($this->getCreate());
			
			return $result;
		}

		/**
		 * @param {String} where
		 * @param {String} order
		 * @param {Boolean} wp
		 * @param {Array}
		 */
		public function read($where, $order, $wp) {
			$line = 0;

			$this->setRead($where, $order);
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($line, "estabelecimento_produtos.id", $row["estabelecimento_produtos.id"]);
				$this->setResponse($line, "estabelecimento_produtos.cadastro", modelDateTime($row["estabelecimento_produtos.cadastro"]));
				$this->setResponse($line, "estabelecimento_produtos.modificado", modelDateTime($row["estabelecimento_produtos.modificado"]));
				$this->setResponse($line, "estabelecimento_produtos.estabelecimento", $row["estabelecimento_produtos.estabelecimento"]);
				$this->setResponse($line, "estabelecimentos.estabelecimento", $row["estabelecimentos.estabelecimento"]);
				$this->setResponse($line, "estabelecimento_produtos.produto", $row["estabelecimento_produtos.produto"]);
				$this->setResponse($line, "produtos.produto", $row["produtos.produto"]);
			
				$this->setResponse($line, "estabelecimento_produtos.line", $line);
			
				$line++;
				
				if ($wp)
					$this->setDivLine($line);
			}

			$this->connection->free($result);
			
			if ($wp && $line > 0) {
				$this->checkDivLine($line);
				
				$this->setSize($where);
			}

			return $this->getResponse();
		}

		/**
		 * @param {Estabelecimento_produtos} estabelecimento_produtos 
		 * @return {Boolean}
		 */
		public function update($estabelecimento_produtos) {
			$result = "";
			
			$this->setUpdate($estabelecimento_produtos, "estabelecimento_produtos.id = " . $estabelecimento_produtos->getId());
			$result = $this->connection->execute($this->getUpdate());

			return $result;
		}

		/**
		 * @param {String} where
		 * @return {Boolean}
		 */
		public function delete($where) {
			$result = "";
			
			$this->setDelete($where);
			$result = $this->connection->execute($this->getDelete());

			return $result;
		}
		
		/**
		 * @param {Integer} selected
		 * @param {String} order
		 * @return {Array}
		 */
		public function combo($selected, $order) {
			$size = 0;

			$this->setRead("", $order);
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($size, "estabelecimento_produtos.id", $row["estabelecimento_produtos.id"]);
				$this->setResponse($size, "estabelecimento_produtos.cadastro", $row["estabelecimento_produtos.cadastro"]);
			
				if ($row["estabelecimento_produtos.id"] == $selected)
					$this->setResponse($size, "estabelecimento_produtos.selected", "selected");
				else
					$this->setResponse($size, "estabelecimento_produtos.selected", "");
					
				$size++;
			}
			
			$this->connection->free($result);
			
			$this->setResponse(0, "size", $size);

			return $this->getResponse();
		}
		
		/**
		 * @param {String} where
		 * @return {Array}
		 */
		public function comboScr($where) {
			$size = 0;

			$this->setRead($where, "");
			$result = $this->connection->execute($this->getRead());

			while ($row = $result->fetch_assoc()) {
				$this->setResponse($size, "estabelecimento_produtos.id", $row["estabelecimento_produtos.id"]);
				$this->setResponse($size, "estabelecimento_produtos.cadastro", $row["estabelecimento_produtos.cadastro"]);
				$this->setResponse($size, "estabelecimento_produtos.selected", "selected");
					
				$size++;
			}
			
			$this->connection->free($result);
			
			$this->setResponse(0, "size", $size);

			return $this->getResponse();
		}

	}

?>