<?php

	/**
	 * Generated by Getz Framework
	 * 
	 * @author Mario Sakamoto <mskamot@gmail.com>
	 * @see https://wtag.com.br/getz
	 */

	use lib\getz;
	use src\model;	 
	
	require_once($_DOCUMENT_ROOT . "/lib/getz/Activator.php");


	

	if ($method == "page") {
		
		$daoFactory->beginTransaction();
		$where = "";
		if ($search != "") {
			$where = "produtos.produto LIKE \"%" . $search . "%\"";
		}
		$response["produtos"] = $daoFactory->getProdutosDao()->read($where, "produtos.produto ASC", true);
		for ($x = 0; $x < sizeof($response["produtos"]); $x++) {
			$response["produtos"][$x]["estabelecimento_produtos"] = $daoFactory->getEstabelecimento_produtosDao()->read(
					"estabelecimento_produtos.produto = " . $response["produtos"][$x]["produtos.id"], "", true);
			for ($y = 0; $y < sizeof($response["produtos"][$x]["estabelecimento_produtos"]); $y++) {
				$response["produtos"][$x]["estabelecimento_produtos"][$y]["estabelecimento_produtos_preco"] = 
				$daoFactory->getEstabelecimento_produtos_precoDao()->read(
						"estabelecimento_produtos_preco.estabelecimeto_produtos = " . 
						$response["produtos"][$x]["estabelecimento_produtos"][$y]["estabelecimento_produtos.id"], "", 
						true);
			}
			
		}
		$daoFactory->close();

		$response["print"] = "true";
		echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/header.html");
		echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/table.html", $response);
		echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/table_dinamic.html", $response);
		echo $view->parse($_DOCUMENT_ROOT . $_PACKAGE . "/html/footer.html");
	}

?>